---
- name: Ensure dotfiles repository is cloned locally.
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_local_destination }}"
    version: main
    accept_hostkey: "{{ dotfiles_repo_accept_hostkey }}"
  become: false

- name: Ensure setup.sh has execute permissions
  file:
    path: "{{ dotfiles_repo_local_destination }}/setup.sh"
    mode: '0755'
  become: false

- name: Run setup.sh script
  shell: |
    source ~/workspaces/dotfiles/.zshrc
    {{ dotfiles_repo_local_destination }}/setup.sh
  args:
    chdir: "{{ dotfiles_repo_local_destination }}"
  become: false